name: Run Tests

on: [push]

jobs:
  main:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Create build directory
        run: cmake -E make_directory ${{ runner.workspace }}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: cmake $GITHUB_WORKSPACE
      - name: Build (debug)
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --config Debug
      - name: Test (debug)
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: ctest -C Debug
      - name: Build (release)
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --config Release
      - name: Test (release)
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: ctest -C Release
